FROM openjdk:10

ENV VERSION=3.14.0

RUN mkdir /jena
RUN mkdir /fuseki

RUN mkdir /QualiChain


RUN wget https://downloads.apache.org/jena/binaries/apache-jena-fuseki-$VERSION.tar.gz -P /tmp \
    && tar -zxvf /tmp/apache-jena-fuseki-$VERSION.tar.gz -C /tmp \
    && mv -v /tmp/apache-jena-fuseki-$VERSION/* /fuseki

# RUN wget https://downloads.apache.org/jena/binaries/apache-jena-$VERSION.tar.gz -P /tmp \
#    && tar -zxvf /tmp/apache-jena-$VERSION.tar.gz -C /tmp \
#    && mv -v /tmp/apache-jena-$VERSION/* /jena

COPY QualiChain_2020-04-27_12-44-49.nq /fuseki/

# RUN jena/bin/tdbloader2 --loc /QualiChain /fuseki/QualiChain_2020-04-27_12-44-49.nq

EXPOSE 3030

COPY script_fuseki.sh /
RUN chmod +x /script_fuseki.sh
RUN chmod +x /fuseki/fuseki-server

ENTRYPOINT ["/bin/bash", "/script_fuseki.sh"]


